---

- name: Install apache
  hosts: all
  become: true
  tasks:

    - name: Install packages
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: true
